config/routes.rb
Ctttest::Application.routes.draw do
  match 'login' => 'users#login'
  match 'signup' => 'users#signup'
  match 'logout' => 'users#logout'

  resources :projects do
    member do
      match 'assign', :via => [:get, :post]
    end
    resources :stories do
      match 'adjust_order', :on => :collection, :via => :post
    end
  end

  resources :users do
    match 'recruit', :on => :collection, :via => [:get, :post]
    match 'dismiss', :on => :member, :via => :post
  end

  root :to => "projects#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

  has_many :stories, :foreign_key => 'requestor_id'
  has_many :responsibilities, :class_name => 'Story', :foreign_key => 'responson'
  has_one :account, :foreign_key => 'owner_id', :dependent => :destroy

  has_many :projects_developers, :foreign_key => 'developer_id'
  has_many :projects, :through => :projects_developers
  has_many :accounts_team_members, :foreign_key => 'team_member_id'
  has_many :assigned_accounts, :through => :accounts_team_members, :source => :account
  has_many :owned_projects, :through => :account, :source => :projects

  def developers
    owned_projects.collect {|project| project.developers}.flatten
  end

  def developer?( project_id = nil )
    if project_id
      projects.any? { |project| project.id == project_id }
    else
      projects.size > 0
    end
  end

  def owner?( account_id = nil )
    if account_id
      account_id == account.id
    else
      !account.nil?
    end
  end

  def generate_password
    if Rails.env.development?
      pass = 'random'
    else
      pass = SecureRandom.hex(8)
    end

    self.password = self.password_confirmation = pass
  end

  def assign_developers( project_id, developer_ids )
    project = Project.find( project_id, :include => :developers )

    begin
      project.developers = User.find(developer_ids.to_a)
    rescue
      project.developers = []
    end

    project.save
  end



  def save_with_account_and_become_team_member
    self.account = Account.new( {:owner_id => id} )
    self.account.team_members << self

    save
  end


  def add_team_member( acc_id = self.account.id, member = self )
    if member.is_a?(Integer)
      team_member_id = member
    elsif member.is_a?(User)
      team_member_id = member.id
    end

    relation = AccountsTeamMember.new( :account_id => acc_id, :team_member_id => team_member_id )
    relation.save
  end

  def recruit_team_members( recruit_ids )
    account.team_members = [self] + User.find(recruit_ids).to_a
    save
  end


  def dismiss( member )
    if member.is_a?( Integer )
      member = User.find( member )
    end

    account.team_members -= [member]
    save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_auth, :only => [:index, :logout]
  before_filter :require_owner, :only => :index
  load_and_authorize_resource :except => [:login, :logout, :signup, :index, :recruit]
  authorize_resource :only => :recruit

  def login
    @user_session = UserSession.new

    if request.post?
      # just to be sure, seems like authlogic does not reset it by itself
      reset_session
      session = UserSession.new(params[:user_session])
      if session.save
        flash[:notice] = 'User authenticated. Welcome inside.'
        redirect_to root_path
      else
        flash[:error] = 'Authentication failed. Raising an eybrow.'
      end
    end
  end

  def signup
   @user = User.new
   if request.post?
     #raise params.to_yaml
     # mass assignment protection for id in application.rb
     @user.attributes = params[:user]
     if @user.save_with_account_and_become_team_member
       flash[:notice] = 'Congratulations. You have signud up succesfully'
       redirect_to root_path
     end
   end
  end

  def logout
    current_user_session.destroy
    flash[:notice] = 'Goodbye. Remember me well.'
    redirect_to login_path
  end
 

  # GET /users
  def index
    @users = current_user.account.team_members

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  def show
    #@user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /users/new
  def new
    #@user = User.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /users/1/edit
  def edit
    #@user = User.find(params[:id])
  end

  # POST /users
  def create
    #@user = User.new(params[:user])
    @user.generate_password

    respond_to do |format|
      if @user.save_without_session_maintenance
        current_user.add_team_member( current_user.account.id, @user )
        Postman.invitation(@user.email, @user.password).deliver

        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /users/1
  def update
    #@user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /users/1
  def destroy
    #@user = User.find(params[:id])

    if @user.id == current_user.id
      flash.now[:notice] = 'You have just destroyed yourself. Destroying your session too'
      current_user_session.destroy
    end

    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
    end
  end

  def recruit
    @users = User.where( 'id != ?', current_user.id )
    @team_members = current_user.account.team_members
    recruits = params[:recruits].nil? ? [] : params[:recruits].keys

    if request.post?
      current_user.recruit_team_members( recruits )
      flash[:notice] = 'Team updated'
      redirect_to users_path
    end
  end

  def dismiss
    current_user.dismiss( @user )

    respond_to do |format|
      format.html { redirect_to(users_url) }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :url => {:controller => :users, :action => action}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <% if action == 'signup' %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render :partial => 'form', :locals => {:action => 'update', :submit => 'Update User'} %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing team members</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <% if can? :read, user %>
      <td><%= link_to 'Show', user %></td>
    <% end %>
    <% if can? :update, user %>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% end %>
    <% if can? :dismiss, user %>
      <td><%= link_to 'Dismiss', dismiss_user_path(user), :confirm => 'Are you sure?', :method => :post %></td>
    <% end %>
    <% if can? :destroy, user %>
      <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, User %>
  <%= link_to 'New Team Member', new_user_path %>
<% end %>
<% if can? :recruit, User %>
  | <%= link_to 'Recruit Team Members', recruit_users_path %>
<% end %>

app/views/users/login.html.erb
<h1>Please provide your credentials</h1>
<% form_for @user_session, :url => login_path do |f| %>
  <%= f.text_field :email %> <br />
  <%= f.label :email %><br />
  <%= f.password_field :password %> <br />
  <%= f.label :password %><br />
    
  <%= submit_tag 'Authenticate' %>
<% end %>

<div>
  You can also <%= link_to 'sign up', signup_path %> and get a free account
</div>

app/views/users/new.html.erb
<h1>New Team Member</h1>

<%= render :partial => 'form', :locals => {:action => 'create', :submit => 'Create User'} %>

<%= link_to 'Back', users_path %>

app/views/users/recruit.html.erb
<h1>Recruit members</h1>

<% if @users.empty? %>
  <div>Nobody to recruit</div>
<% else %>
  <% form_tag recruit_users_path do %>
    <% @users.each do |u| %>
      <%= check_box_tag "recruits[#{u.id}]", true, @team_members.include?(u) %> <%= label_tag u.email %><br />
    <% end %>
    <%= submit_tag 'Submit' %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signup.html.erb
<h1></h1>

<%= render :partial => 'form', :locals => {:action => 'signup', :submit => 'Signup'} %>

<%= link_to 'Back', login_path %>