config/routes.rb
Ctttest::Application.routes.draw do
  match 'login' => 'users#login'
  match 'signup' => 'users#signup'
  match 'logout' => 'users#logout'

  resources :projects do
    member do
      match 'assign', :via => [:get, :post]
    end
    resources :stories do
      match 'adjust_order', :on => :collection, :via => :post
    end
  end

  resources :users do
    match 'recruit', :on => :collection, :via => [:get, :post]
    match 'dismiss', :on => :member, :via => :post
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :title, :description, :manager_id, :account_id

  belongs_to :account
  belongs_to :manager, :class_name => 'User'
  has_many :stories, :order => :position, :dependent => :destroy
  has_many :projects_developers
  has_many :developers, :through => :projects_developers

  def count_stories
    not_ready_count, waiting_count, in_progress_count, accepted_count, rejected_count = 0, 0, 0, 0, 0
    stories.each {|story| 
      case story.life_cycle_phase.phase
        when 'not ready'
          not_ready_count += 1
        when 'waiting'
          waiting_count += 1
        when 'started', 'finished', 'delivered'
          in_progress_count += 1
        when 'accepted'
          accepted_count += 1
        when 'rejected'
          rejected_count += 1
      end
    }
    
    {:not_ready => not_ready_count, :waiting => waiting_count, :in_progress => in_progress_count, :accepted => accepted_count, :rejected => rejected_count,
     :total => stories.size}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # this allows the user on the index page even if he has no projects, which I could not achieve with CanCan
  before_filter :require_auth, :only => :index
  load_and_authorize_resource :except => :index

  def assign
    @team_members = current_user.account.team_members
    @developers = current_user.developers
    if request.post?
      assigned_developers = params[:assigned_developers].nil? ? [] : params[:assigned_developers].keys
      if current_user.assign_developers(@project.id, assigned_developers)
        flash[:notice] = 'Developers updated'
        redirect_to project_path(@project)
      else
        flash[:error] = 'Developers could not be saved'
      end
    end
  end  


  # GET /projects
  def index
    @owned_projects = current_user.owned_projects
    @projects = current_user.projects

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id], :include => [:manager, :developers, {:stories => [:requestor, :responson, :life_cycle_phase]}])
    @counts = @project.count_stories

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /projects/new
  def new
    #@project = Project.new
    @potencional_managers = current_user.account.team_members

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /projects/1/edit
  def edit
    #@project = Project.find(params[:id])
    @potencional_managers = current_user.account.team_members
  end

  # POST /projects
  def create
    #@project = Project.new(params[:project])
    @potencional_managers = current_user.account.team_members
    @project.account_id ||= current_user.account.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /projects/1
  def update
    #@project = Project.find(params[:id])
    @potencional_managers = current_user.account.team_members
    @project.account_id ||= current_user.account.id

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    #@project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= collection_select(:project, :manager_id, @potencional_managers, :id, :email) %>
    <%= f.label :manager_id %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/assign.html.erb
<h1>You can choose from these members of your team</h1>

<% form_tag assign_project_path(@project) do %>
<% @team_members.each do |member| %>
  <%= check_box_tag "assigned_developers[#{member.id}]", true, @developers.include?(member) %> <%= label_tag member.email %><br />
<% end %>

<%= submit_tag 'Submit' %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<% if current_user.owner? %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Client</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<h3>You now own <%= pluralize(@owned_projects.count, "project") %></h3>
<% @owned_projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.client %></td>
    <td><%= project.deadline %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<h3>You are a developer on <%= pluralize(@projects.count, "project") %></h3>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Client</th>
    <th>Deadline</th>
    <th></th>
  </tr>
<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.client %></td>
    <td><%= project.deadline %></td>
    <td>
      <% if can? :read, project %>
        <%= link_to 'Show', project %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, Project %>
<%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Client:</b>
  <%= @project.client %>
</p>

<p>
  <b>Deadline:</b>
  <%= @project.deadline %>
</p>

<p>
  <b>Manager:</b>
  <%= @project.manager.email %>
</p>


<h3>This project has <%= pluralize(@counts[:total], 'story') %> (<%= @counts[:not_ready] %> not ready,
                                                                 <%= @counts[:waiting] %> waiting, 
                                                                 <%= @counts[:in_progress] %> in progress,
                                                                 <%= @counts[:accepted] %> accepted and
                                                                 <%= @counts[:rejected] %> rejected)</h3>
<div>
  <ol id="stories_list">
    <% @project.stories.each do |story| %>
      <li id="item_<%= story.id %>">
        <div><%= story.requestor.email rescue 'DELETED' %> has written:</div>
        <div><%= story.title %></div>
        <div><%= story.description %></div>
        <div><%= story.life_cycle_phase.phase %></div>
        <div><%= story.responson.email rescue 'DELETED' %> is responsible for this</div>
        <div>
          <% if can? :read, story %>
            <%= link_to 'Show', project_story_path(@project, story) %><br />
          <% end %>
          <% if can? :update, story %>
            <%= link_to 'Edit', edit_project_story_path(@project, story) %><br />
          <% end %>
          <% if can? :destroy, story %>
            <%= link_to 'Delete', project_story_path(@project, story), :method => :delete, :confirm => 'Are you sure?' %><br />
          <% end %>
        </div>
      </li>
    <% end %>
  </ol>
  <% if can? :adjust_order, @project %>
    <%= sortable_element "stories_list", :url => adjust_order_project_stories_path(@project),
                                         :complete => visual_effect(:highlight, "stories_list") %>
  <% end %>
</div>

<h3>This project has <%= pluralize(@project.developers.count, 'developer') %></h3>
<div class="developers_list">
  <ul>
    <% @project.developers.each do |developer| %>
      <li>
        <%= developer.email %>
      </li>
    <% end %>
  </ul>
</div>


<% if can? :update, @project %>
  <%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Assign developers', assign_project_path(@project) %> | 
<% end %>
<% if can? :create, Story %>
  <%= link_to 'Write a story', new_project_story_path(@project) %> | 
<% end %>
<%= link_to 'Back', projects_path %>